version: '3.8'

services:
  # Backend Spring Boot
  backend:
    build:
      context: ../backend-spring
      dockerfile: Dockerfile
    container_name: notes-backend
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/notes
      - JWT_SECRET=your-secret-key-change-this-in-production-with-a-very-long-secure-random-string
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000,http://frontend:5173
    volumes:
      - backend-data:/data
      - ../backend-spring/logs:/app/logs
    networks:
      - notes-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Frontend Web React
  frontend:
    build:
      context: ../frontend-web
      dockerfile: Dockerfile
    container_name: notes-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:9090
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge

volumes:
  backend-data:
    driver: local

